on:
  - push
  - pull_request

jobs:
  release:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 3
      fail-fast: true
      matrix:
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1.0.0
        with:
          version: '1.15'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Go version
        run: go version

      - name: Test
        run: |
          go test ./...

      - if: failure()
        run: ls -R
